// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/kvk2030_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// novaSitPovodi
Rcpp::XPtr<SitPovodi> novaSitPovodi();
RcppExport SEXP _kvk2030_novaSitPovodi() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(novaSitPovodi());
    return rcpp_result_gen;
END_RCPP
}
// getSitPovodiParameter
int getSitPovodiParameter(Rcpp::XPtr<SitPovodi> ptr);
RcppExport SEXP _kvk2030_getSitPovodiParameter(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SitPovodi> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(getSitPovodiParameter(ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kvk2030_novaSitPovodi", (DL_FUNC) &_kvk2030_novaSitPovodi, 0},
    {"_kvk2030_getSitPovodiParameter", (DL_FUNC) &_kvk2030_getSitPovodiParameter, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_kvk2030(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
